package ru.pavlenov.scala.homework.coursera

/**
 * ⓭ + 43
 * Какой сам? by Pavlenov Semen 19.10.14.
 * https://stepic.org/lesson/Hidden-Messages-in-the-Replication-Origin-2/step/6?course=Bioinformatics-Algorithms&unit=401
 */
object Step1_2_6 {

  def start() = {

    val text = "CTCGTCTCGCTTGCTCTCGCTTGTCTCGCTTACTCGCTTAACTCGCTTCTCGCTTCTCGCTTATAGCTCGCTTAACTCTCGCTTAGAACTCGCTTTGCTCGCTTCGCACTCGCTTGTGGCGACCTCGCTTGTCCTCGCTTCCTCGCTTCTCGCTTTCTCGCTTCTCGCTTAGCTCGCTTGAGCCTCGCTTGTTTGGTCCTCGCTTCCTCGCTTACTCGCTTGCTCGCTTAGCTCGCTTCTCGCTTCTCGCTTTTGATTCTCGCTTGCTCGCTTGGGGATTCTCGCTTCTCGCTTACCTCGCTTATTGCACTCGCTTGGAGCGTTACTCGCTTGCTCGCTTCATCCTCGCTTAGAAGAAGACTCGCTTTACTCGCTTCCTTGGACTCGCTTTGAACCTTTGAACTGCTAACTCGCTTGCACTCGCTTATCTCGCTTGCTCGCTTAGACAAGGCTCGCTTCTCGCTTCTCGCTTAATGAACGAGGGGGTCTCGCTTCCCACTCGCTTTCCATTAATATCTCGCTTGTTACTGCTCGCTTGTCGGCTCGCTTCCTCGCTTTCGGACGGGCTCGCTTAATAGCTCGCTTAGATTCTCGCTTGCTCGCTTATTCTCGCTTACTCGCTTATATACTCGCTTTCCGAGCTCGCTTCAAAGGCTCTCGCTTGCTCGCTTCCTCGCTTGCACGCCTCGCTTGACTCGCTTCTCGCTTCAGCTCGCTTGCTCGCTTACTCGCTTGTACTCGCTTACCTCGCTTGTGCTCGCTTCGAACTCGCTTAAAAGTCTCGCTTCTCGCTTGTTATCTCGCTTCCTCGCTTACCTTGTGCACTCGCTTCCTCGCTTGCTCGCTTGCTCGCTTCTCGCTTGCTCGCTTCAACTCGCTTTCTCGCTTACTCGCTTCCCTCGCTTCTCGCTTCTCGCTTCTCCTGGGCTCGCTTTCTCGCTTTAC"
    val pattern = "CTCGCTTCT"

    println(patternCount(text, pattern))

  }

  def patternCount(text: String, pattern: String) = {
    var count = 0
    val textLen = text.length
    val patternLen = pattern.length
    val diff = textLen - patternLen
    for (i ← 0 to diff) {
      if (text.substring(i, patternLen + i) == pattern)
        count += 1
    }
    count
  }

}
